spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/agropecuario_pos?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Server config
server.port=8080
server.error.include-message=always

# Logging config
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT Keys
agropecuario.app.jwtSecret=4d8a1768b55d9d7fd32bbcaad67b2d56d353982e0e4b47eb5f0ef3ad492a5d2c
agropecuario.app.jwtExpirationMs=86400000

# Mail Configuration (Dummy config to allow context load)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manuelortizmejicano100@gmail.com
spring.mail.password=uafporypgfytcmzq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Database Encryption Key (must be 16, 24, or 32 bytes for AES)
agropecuario.app.dbEncryptionKey=1234567890123456

# ========================================================
# HACIENDA FACTURACION ELECTRONICA — AMBIENTE: PRUEBAS
# ========================================================

# --- Autenticación OAuth (IdP Hacienda) ---
hacienda.api.token.url=https://idp.comprobanteselectronicos.go.cr/auth/realms/rut-stag/protocol/openid-connect/token
hacienda.api.client.id=api-stag
hacienda.api.username=cpf-02-0860-0363@stag.comprobanteselectronicos.go.cr
hacienda.api.password=$*@sz7RU^_1T^wQcu90A

# --- Endpoint de Envío y Consulta ---
hacienda.api.recepcion.url=https://api-sandbox.comprobanteselectronicos.go.cr/recepcion/v1/recepcion

# --- Datos del Emisor ---
hacienda.emisor.nombre=MANUEL SALVADOR MEJICANO ORTIZ
hacienda.emisor.cedula=208600363
hacienda.emisor.tipo.cedula=01
hacienda.emisor.provincia=2
hacienda.emisor.canton=13
hacienda.emisor.distrito=07
hacienda.emisor.actividad.economica=512102
hacienda.emisor.email=manuelortizmejicano100@gmail.com
hacienda.emisor.telefono=70280576

# --- Llave Criptográfica (.p12) ---
hacienda.crypto.keystore.path=C:/certificados/certificado.p12
hacienda.crypto.keystore.password=110420

# --- Ambiente: 'stag' (pruebas) o 'prod' (produccion) ---
hacienda.ambiente=stag

# ========================================================
# PARA PASAR A PRODUCCION, CAMBIAR:
#   token.url → .../rut/...
#   client.id → api-prod
#   recepcion.url → https://api.comprobanteselectronicos.go.cr/recepcion/v1/recepcion
#   keystore.path → ruta al .p12 de PRODUCCION
#   ambiente → prod
# ========================================================
